package com.flopster101.siliconplayer

import android.content.Context
import android.content.SharedPreferences

internal fun buildSettingsScreenStateFromStateHolders(
    selectedPluginName: String?,
    autoPlayOnTrackSelect: Boolean,
    openPlayerOnTrackSelect: Boolean,
    autoPlayNextTrackOnEnd: Boolean,
    preloadNextCachedRemoteTrack: Boolean,
    playlistWrapNavigation: Boolean,
    previousRestartsAfterThreshold: Boolean,
    fadePauseResume: Boolean,
    audioFocusInterrupt: Boolean,
    audioDucking: Boolean,
    persistRepeatMode: Boolean,
    themeMode: ThemeMode,
    useMonet: Boolean,
    monetAvailable: Boolean,
    rememberBrowserLocation: Boolean,
    showParentDirectoryEntry: Boolean,
    showFileIconChipBackground: Boolean,
    sortArchivesBeforeFiles: Boolean,
    browserNameSortMode: BrowserNameSortMode,
    recentFoldersLimit: Int,
    recentFilesLimit: Int,
    pressBackTwiceToExit: Boolean,
    keepScreenOn: Boolean,
    playerArtworkCornerRadiusDp: Int,
    showAudioOutputRouteChip: Boolean,
    filenameDisplayMode: FilenameDisplayMode,
    filenameOnlyWhenTitleMissing: Boolean,
    unknownTrackDurationSeconds: Int,
    endFadeApplyToAllTracks: Boolean,
    endFadeDurationMs: Int,
    endFadeCurve: EndFadeCurve,
    visualizationMode: VisualizationMode,
    enabledVisualizationModes: Set<VisualizationMode>,
    visualizationPerformanceMode: VisualizationPerformanceMode,
    visualizationShowDebugInfo: Boolean,
    visualizationKeepScreenOn: Boolean,
    visualizationBarCount: Int,
    visualizationBarSmoothingPercent: Int,
    visualizationBarRoundnessDp: Int,
    visualizationBarOverlayArtwork: Boolean,
    visualizationBarUseThemeColor: Boolean,
    visualizationBarRenderBackend: VisualizationRenderBackend,
    visualizationOscStereo: Boolean,
    visualizationVuAnchor: VisualizationVuAnchor,
    visualizationVuUseThemeColor: Boolean,
    visualizationVuSmoothingPercent: Int,
    visualizationVuRenderBackend: VisualizationRenderBackend,
    ffmpegCapabilities: Int,
    openMptCapabilities: Int,
    vgmPlayCapabilities: Int,
    settingsStates: AppNavigationSettingsStates
): SettingsScreenState {
    return buildSettingsScreenState(
        selectedPluginName = selectedPluginName,
        autoPlayOnTrackSelect = autoPlayOnTrackSelect,
        openPlayerOnTrackSelect = openPlayerOnTrackSelect,
        autoPlayNextTrackOnEnd = autoPlayNextTrackOnEnd,
        preloadNextCachedRemoteTrack = preloadNextCachedRemoteTrack,
        playlistWrapNavigation = playlistWrapNavigation,
        previousRestartsAfterThreshold = previousRestartsAfterThreshold,
        fadePauseResume = fadePauseResume,
        respondHeadphoneMediaButtons = settingsStates.respondHeadphoneMediaButtons.value,
        pauseOnHeadphoneDisconnect = settingsStates.pauseOnHeadphoneDisconnect.value,
        audioFocusInterrupt = audioFocusInterrupt,
        audioDucking = audioDucking,
        audioBackendPreference = settingsStates.audioBackendPreference.value,
        audioPerformanceMode = settingsStates.audioPerformanceMode.value,
        audioBufferPreset = settingsStates.audioBufferPreset.value,
        audioResamplerPreference = settingsStates.audioResamplerPreference.value,
        audioOutputLimiterEnabled = settingsStates.audioOutputLimiterEnabled.value,
        lookaheadClipperMode = settingsStates.lookaheadClipperMode.value,
        audioAllowBackendFallback = settingsStates.audioAllowBackendFallback.value,
        openPlayerFromNotification = settingsStates.openPlayerFromNotification.value,
        persistRepeatMode = persistRepeatMode,
        themeMode = themeMode,
        useMonet = useMonet,
        monetAvailable = monetAvailable,
        rememberBrowserLocation = rememberBrowserLocation,
        showParentDirectoryEntry = showParentDirectoryEntry,
        showFileIconChipBackground = showFileIconChipBackground,
        sortArchivesBeforeFiles = sortArchivesBeforeFiles,
        browserNameSortMode = browserNameSortMode,
        recentFoldersLimit = recentFoldersLimit,
        recentFilesLimit = recentFilesLimit,
        pressBackTwiceToExit = pressBackTwiceToExit,
        urlCacheClearOnLaunch = settingsStates.urlCacheClearOnLaunch.value,
        urlCacheMaxTracks = settingsStates.urlCacheMaxTracks.intValue,
        urlCacheMaxBytes = settingsStates.urlCacheMaxBytes.longValue,
        archiveCacheClearOnLaunch = settingsStates.archiveCacheClearOnLaunch.value,
        archiveCacheMaxMounts = settingsStates.archiveCacheMaxMounts.intValue,
        archiveCacheMaxBytes = settingsStates.archiveCacheMaxBytes.longValue,
        archiveCacheMaxAgeDays = settingsStates.archiveCacheMaxAgeDays.intValue,
        cachedSourceFiles = settingsStates.cachedSourceFiles.value,
        keepScreenOn = keepScreenOn,
        playerArtworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        showAudioOutputRouteChip = showAudioOutputRouteChip,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing,
        unknownTrackDurationSeconds = unknownTrackDurationSeconds,
        endFadeApplyToAllTracks = endFadeApplyToAllTracks,
        endFadeDurationMs = endFadeDurationMs,
        endFadeCurve = endFadeCurve,
        visualizationMode = visualizationMode,
        enabledVisualizationModes = enabledVisualizationModes,
        visualizationPerformanceMode = visualizationPerformanceMode,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        visualizationKeepScreenOn = visualizationKeepScreenOn,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        pluginCore = buildSettingsPluginCoreStateFromStateHolders(
            settingsStates = settingsStates,
            ffmpegCapabilities = ffmpegCapabilities,
            openMptCapabilities = openMptCapabilities,
            vgmPlayCapabilities = vgmPlayCapabilities
        )
    )
}

private fun buildSettingsPluginCoreStateFromStateHolders(
    settingsStates: AppNavigationSettingsStates,
    ffmpegCapabilities: Int,
    openMptCapabilities: Int,
    vgmPlayCapabilities: Int
): SettingsPluginCoreState {
    return SettingsPluginCoreState(
        ffmpegSampleRateHz = settingsStates.ffmpegCoreSampleRateHz.intValue,
        ffmpegGaplessRepeatTrack = settingsStates.ffmpegGaplessRepeatTrack.value,
        ffmpegCapabilities = ffmpegCapabilities,
        openMptSampleRateHz = settingsStates.openMptCoreSampleRateHz.intValue,
        openMptCapabilities = openMptCapabilities,
        vgmPlaySampleRateHz = settingsStates.vgmPlayCoreSampleRateHz.intValue,
        vgmPlayCapabilities = vgmPlayCapabilities,
        gmeSampleRateHz = settingsStates.gmeCoreSampleRateHz.intValue,
        crsidSampleRateHz = settingsStates.crsidCoreSampleRateHz.intValue,
        sidPlayFpSampleRateHz = settingsStates.sidPlayFpCoreSampleRateHz.intValue,
        lazyUsf2SampleRateHz = settingsStates.lazyUsf2CoreSampleRateHz.intValue,
        adPlugSampleRateHz = settingsStates.adPlugCoreSampleRateHz.intValue,
        hivelyTrackerSampleRateHz = settingsStates.hivelyTrackerCoreSampleRateHz.intValue,
        klystrackSampleRateHz = settingsStates.klystrackCoreSampleRateHz.intValue,
        furnaceSampleRateHz = settingsStates.furnaceCoreSampleRateHz.intValue,
        uadeSampleRateHz = settingsStates.uadeCoreSampleRateHz.intValue,
        adPlugOplEngine = settingsStates.adPlugOplEngine.intValue,
        lazyUsf2UseHleAudio = settingsStates.lazyUsf2UseHleAudio.value,
        vio2sfInterpolationQuality = settingsStates.vio2sfInterpolationQuality.intValue,
        sc68SamplingRateHz = settingsStates.sc68SamplingRateHz.intValue,
        sc68Asid = settingsStates.sc68Asid.intValue,
        sc68DefaultTimeSeconds = settingsStates.sc68DefaultTimeSeconds.intValue,
        sc68YmEngine = settingsStates.sc68YmEngine.intValue,
        sc68YmVolModel = settingsStates.sc68YmVolModel.intValue,
        sc68AmigaFilter = settingsStates.sc68AmigaFilter.value,
        sc68AmigaBlend = settingsStates.sc68AmigaBlend.intValue,
        sc68AmigaClock = settingsStates.sc68AmigaClock.intValue,
        uadeFilterEnabled = settingsStates.uadeFilterEnabled.value,
        uadeNtscMode = settingsStates.uadeNtscMode.value,
        uadePanningMode = settingsStates.uadePanningMode.intValue,
        hivelyTrackerPanningMode = settingsStates.hivelyTrackerPanningMode.intValue,
        hivelyTrackerMixGainPercent = settingsStates.hivelyTrackerMixGainPercent.intValue,
        klystrackPlayerQuality = settingsStates.klystrackPlayerQuality.intValue,
        furnaceYm2612Core = settingsStates.furnaceYm2612Core.intValue,
        furnaceSnCore = settingsStates.furnaceSnCore.intValue,
        furnaceNesCore = settingsStates.furnaceNesCore.intValue,
        furnaceC64Core = settingsStates.furnaceC64Core.intValue,
        furnaceGbQuality = settingsStates.furnaceGbQuality.intValue,
        furnaceDsidQuality = settingsStates.furnaceDsidQuality.intValue,
        furnaceAyCore = settingsStates.furnaceAyCore.intValue,
        crsidClockMode = settingsStates.crsidClockMode.intValue,
        crsidSidModelMode = settingsStates.crsidSidModelMode.intValue,
        crsidQualityMode = settingsStates.crsidQualityMode.intValue,
        crsidFilter6581Preset = settingsStates.crsidFilter6581Preset.intValue,
        sidPlayFpBackend = settingsStates.sidPlayFpBackend.intValue,
        sidPlayFpClockMode = settingsStates.sidPlayFpClockMode.intValue,
        sidPlayFpSidModelMode = settingsStates.sidPlayFpSidModelMode.intValue,
        sidPlayFpFilter6581Enabled = settingsStates.sidPlayFpFilter6581Enabled.value,
        sidPlayFpFilter8580Enabled = settingsStates.sidPlayFpFilter8580Enabled.value,
        sidPlayFpDigiBoost8580 = settingsStates.sidPlayFpDigiBoost8580.value,
        sidPlayFpFilterCurve6581Percent = settingsStates.sidPlayFpFilterCurve6581Percent.intValue,
        sidPlayFpFilterRange6581Percent = settingsStates.sidPlayFpFilterRange6581Percent.intValue,
        sidPlayFpFilterCurve8580Percent = settingsStates.sidPlayFpFilterCurve8580Percent.intValue,
        sidPlayFpReSidFpFastSampling = settingsStates.sidPlayFpReSidFpFastSampling.value,
        sidPlayFpReSidFpCombinedWaveformsStrength = settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue,
        gmeTempoPercent = settingsStates.gmeTempoPercent.intValue,
        gmeStereoSeparationPercent = settingsStates.gmeStereoSeparationPercent.intValue,
        gmeEchoEnabled = settingsStates.gmeEchoEnabled.value,
        gmeAccuracyEnabled = settingsStates.gmeAccuracyEnabled.value,
        gmeEqTrebleDecibel = settingsStates.gmeEqTrebleDecibel.intValue,
        gmeEqBassHz = settingsStates.gmeEqBassHz.intValue,
        gmeSpcUseBuiltInFade = settingsStates.gmeSpcUseBuiltInFade.value,
        gmeSpcInterpolation = settingsStates.gmeSpcInterpolation.intValue,
        gmeSpcUseNativeSampleRate = settingsStates.gmeSpcUseNativeSampleRate.value,
        vgmPlayLoopCount = settingsStates.vgmPlayLoopCount.intValue,
        vgmPlayAllowNonLoopingLoop = settingsStates.vgmPlayAllowNonLoopingLoop.value,
        vgmPlayVsyncRate = settingsStates.vgmPlayVsyncRate.intValue,
        vgmPlayResampleMode = settingsStates.vgmPlayResampleMode.intValue,
        vgmPlayChipSampleMode = settingsStates.vgmPlayChipSampleMode.intValue,
        vgmPlayChipSampleRate = settingsStates.vgmPlayChipSampleRate.intValue,
        vgmPlayChipCoreSelections = settingsStates.vgmPlayChipCoreSelections.value,
        openMptStereoSeparationPercent = settingsStates.openMptStereoSeparationPercent.intValue,
        openMptStereoSeparationAmigaPercent = settingsStates.openMptStereoSeparationAmigaPercent.intValue,
        openMptInterpolationFilterLength = settingsStates.openMptInterpolationFilterLength.intValue,
        openMptAmigaResamplerMode = settingsStates.openMptAmigaResamplerMode.intValue,
        openMptAmigaResamplerApplyAllModules = settingsStates.openMptAmigaResamplerApplyAllModules.value,
        openMptVolumeRampingStrength = settingsStates.openMptVolumeRampingStrength.intValue,
        openMptFt2XmVolumeRamping = settingsStates.openMptFt2XmVolumeRamping.value,
        openMptMasterGainMilliBel = settingsStates.openMptMasterGainMilliBel.intValue,
        openMptSurroundEnabled = settingsStates.openMptSurroundEnabled.value
    )
}

internal fun buildSettingsPluginCoreActionsFromStateHolders(
    settingsStates: AppNavigationSettingsStates,
    onOpenVgmPlayChipSettings: () -> Unit = {},
    onPluginSelected: (String) -> Unit = {},
    onPluginEnabledChanged: (String, Boolean) -> Unit = { _, _ -> },
    onPluginPriorityChanged: (String, Int) -> Unit = { _, _ -> },
    onPluginPriorityOrderChanged: (List<String>) -> Unit = {},
    onPluginExtensionsChanged: (String, Array<String>) -> Unit = { _, _ -> }
): SettingsPluginCoreActions {
    return SettingsPluginCoreActions(
        onOpenVgmPlayChipSettings = onOpenVgmPlayChipSettings,
        onPluginSelected = onPluginSelected,
        onPluginEnabledChanged = onPluginEnabledChanged,
        onPluginPriorityChanged = onPluginPriorityChanged,
        onPluginPriorityOrderChanged = onPluginPriorityOrderChanged,
        onPluginExtensionsChanged = onPluginExtensionsChanged,
        onFfmpegSampleRateChanged = { settingsStates.ffmpegCoreSampleRateHz.intValue = it },
        onFfmpegGaplessRepeatTrackChanged = { settingsStates.ffmpegGaplessRepeatTrack.value = it },
        onOpenMptSampleRateChanged = { settingsStates.openMptCoreSampleRateHz.intValue = it },
        onVgmPlaySampleRateChanged = { settingsStates.vgmPlayCoreSampleRateHz.intValue = it },
        onGmeSampleRateChanged = { settingsStates.gmeCoreSampleRateHz.intValue = it },
        onCrsidSampleRateChanged = { settingsStates.crsidCoreSampleRateHz.intValue = it },
        onSidPlayFpSampleRateChanged = { settingsStates.sidPlayFpCoreSampleRateHz.intValue = it },
        onLazyUsf2SampleRateChanged = { settingsStates.lazyUsf2CoreSampleRateHz.intValue = it },
        onAdPlugSampleRateChanged = { settingsStates.adPlugCoreSampleRateHz.intValue = it },
        onHivelyTrackerSampleRateChanged = { settingsStates.hivelyTrackerCoreSampleRateHz.intValue = it },
        onKlystrackSampleRateChanged = { settingsStates.klystrackCoreSampleRateHz.intValue = it },
        onFurnaceSampleRateChanged = { settingsStates.furnaceCoreSampleRateHz.intValue = it },
        onUadeSampleRateChanged = { settingsStates.uadeCoreSampleRateHz.intValue = it },
        onAdPlugOplEngineChanged = { settingsStates.adPlugOplEngine.intValue = it },
        onLazyUsf2UseHleAudioChanged = { settingsStates.lazyUsf2UseHleAudio.value = it },
        onVio2sfInterpolationQualityChanged = { settingsStates.vio2sfInterpolationQuality.intValue = it },
        onSc68SamplingRateHzChanged = { settingsStates.sc68SamplingRateHz.intValue = it },
        onSc68AsidChanged = { settingsStates.sc68Asid.intValue = it },
        onSc68DefaultTimeSecondsChanged = { settingsStates.sc68DefaultTimeSeconds.intValue = it },
        onSc68YmEngineChanged = { settingsStates.sc68YmEngine.intValue = it },
        onSc68YmVolModelChanged = { settingsStates.sc68YmVolModel.intValue = it },
        onSc68AmigaFilterChanged = { settingsStates.sc68AmigaFilter.value = it },
        onSc68AmigaBlendChanged = { settingsStates.sc68AmigaBlend.intValue = it },
        onSc68AmigaClockChanged = { settingsStates.sc68AmigaClock.intValue = it },
        onUadeFilterEnabledChanged = { settingsStates.uadeFilterEnabled.value = it },
        onUadeNtscModeChanged = { settingsStates.uadeNtscMode.value = it },
        onUadePanningModeChanged = { settingsStates.uadePanningMode.intValue = it },
        onHivelyTrackerPanningModeChanged = { settingsStates.hivelyTrackerPanningMode.intValue = it },
        onHivelyTrackerMixGainPercentChanged = { settingsStates.hivelyTrackerMixGainPercent.intValue = it },
        onKlystrackPlayerQualityChanged = { settingsStates.klystrackPlayerQuality.intValue = it },
        onFurnaceYm2612CoreChanged = { settingsStates.furnaceYm2612Core.intValue = it },
        onFurnaceSnCoreChanged = { settingsStates.furnaceSnCore.intValue = it },
        onFurnaceNesCoreChanged = { settingsStates.furnaceNesCore.intValue = it },
        onFurnaceC64CoreChanged = { settingsStates.furnaceC64Core.intValue = it },
        onFurnaceGbQualityChanged = { settingsStates.furnaceGbQuality.intValue = it },
        onFurnaceDsidQualityChanged = { settingsStates.furnaceDsidQuality.intValue = it },
        onFurnaceAyCoreChanged = { settingsStates.furnaceAyCore.intValue = it },
        onCrsidClockModeChanged = { settingsStates.crsidClockMode.intValue = it },
        onCrsidSidModelModeChanged = { settingsStates.crsidSidModelMode.intValue = it },
        onCrsidQualityModeChanged = { settingsStates.crsidQualityMode.intValue = it },
        onCrsidFilter6581PresetChanged = { settingsStates.crsidFilter6581Preset.intValue = it },
        onSidPlayFpBackendChanged = { settingsStates.sidPlayFpBackend.intValue = it },
        onSidPlayFpClockModeChanged = { settingsStates.sidPlayFpClockMode.intValue = it },
        onSidPlayFpSidModelModeChanged = { settingsStates.sidPlayFpSidModelMode.intValue = it },
        onSidPlayFpFilter6581EnabledChanged = { settingsStates.sidPlayFpFilter6581Enabled.value = it },
        onSidPlayFpFilter8580EnabledChanged = { settingsStates.sidPlayFpFilter8580Enabled.value = it },
        onSidPlayFpDigiBoost8580Changed = { settingsStates.sidPlayFpDigiBoost8580.value = it },
        onSidPlayFpFilterCurve6581PercentChanged = {
            settingsStates.sidPlayFpFilterCurve6581Percent.intValue = it
        },
        onSidPlayFpFilterRange6581PercentChanged = {
            settingsStates.sidPlayFpFilterRange6581Percent.intValue = it
        },
        onSidPlayFpFilterCurve8580PercentChanged = {
            settingsStates.sidPlayFpFilterCurve8580Percent.intValue = it
        },
        onSidPlayFpReSidFpFastSamplingChanged = { settingsStates.sidPlayFpReSidFpFastSampling.value = it },
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = {
            settingsStates.sidPlayFpReSidFpCombinedWaveformsStrength.intValue = it
        },
        onGmeTempoPercentChanged = { settingsStates.gmeTempoPercent.intValue = it },
        onGmeStereoSeparationPercentChanged = { settingsStates.gmeStereoSeparationPercent.intValue = it },
        onGmeEchoEnabledChanged = { settingsStates.gmeEchoEnabled.value = it },
        onGmeAccuracyEnabledChanged = { settingsStates.gmeAccuracyEnabled.value = it },
        onGmeEqTrebleDecibelChanged = { settingsStates.gmeEqTrebleDecibel.intValue = it },
        onGmeEqBassHzChanged = { settingsStates.gmeEqBassHz.intValue = it },
        onGmeSpcUseBuiltInFadeChanged = { settingsStates.gmeSpcUseBuiltInFade.value = it },
        onGmeSpcInterpolationChanged = { settingsStates.gmeSpcInterpolation.intValue = it },
        onGmeSpcUseNativeSampleRateChanged = { settingsStates.gmeSpcUseNativeSampleRate.value = it },
        onVgmPlayLoopCountChanged = { settingsStates.vgmPlayLoopCount.intValue = it },
        onVgmPlayAllowNonLoopingLoopChanged = { settingsStates.vgmPlayAllowNonLoopingLoop.value = it },
        onVgmPlayVsyncRateChanged = { settingsStates.vgmPlayVsyncRate.intValue = it },
        onVgmPlayResampleModeChanged = { settingsStates.vgmPlayResampleMode.intValue = it },
        onVgmPlayChipSampleModeChanged = { settingsStates.vgmPlayChipSampleMode.intValue = it },
        onVgmPlayChipSampleRateChanged = { settingsStates.vgmPlayChipSampleRate.intValue = it },
        onVgmPlayChipCoreChanged = { chipKey, selectedValue ->
            settingsStates.vgmPlayChipCoreSelections.value =
                settingsStates.vgmPlayChipCoreSelections.value + (chipKey to selectedValue)
        },
        onOpenMptStereoSeparationPercentChanged = { settingsStates.openMptStereoSeparationPercent.intValue = it },
        onOpenMptStereoSeparationAmigaPercentChanged = {
            settingsStates.openMptStereoSeparationAmigaPercent.intValue = it
        },
        onOpenMptInterpolationFilterLengthChanged = {
            settingsStates.openMptInterpolationFilterLength.intValue = it
        },
        onOpenMptAmigaResamplerModeChanged = { settingsStates.openMptAmigaResamplerMode.intValue = it },
        onOpenMptAmigaResamplerApplyAllModulesChanged = {
            settingsStates.openMptAmigaResamplerApplyAllModules.value = it
        },
        onOpenMptVolumeRampingStrengthChanged = { settingsStates.openMptVolumeRampingStrength.intValue = it },
        onOpenMptFt2XmVolumeRampingChanged = { settingsStates.openMptFt2XmVolumeRamping.value = it },
        onOpenMptMasterGainMilliBelChanged = { settingsStates.openMptMasterGainMilliBel.intValue = it },
        onOpenMptSurroundEnabledChanged = { settingsStates.openMptSurroundEnabled.value = it }
    )
}

internal fun clearAllSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    defaultScopeTextSizeSp: Int,
    selectableVisualizationModes: List<VisualizationMode>,
    onThemeModeChanged: (ThemeMode) -> Unit,
    onUseMonetChanged: (Boolean) -> Unit,
    settingsStates: AppNavigationSettingsStates,
    onAutoPlayOnTrackSelectChanged: (Boolean) -> Unit,
    onOpenPlayerOnTrackSelectChanged: (Boolean) -> Unit,
    onAutoPlayNextTrackOnEndChanged: (Boolean) -> Unit,
    onPreloadNextCachedRemoteTrackChanged: (Boolean) -> Unit,
    onPlaylistWrapNavigationChanged: (Boolean) -> Unit,
    onPreviousRestartsAfterThresholdChanged: (Boolean) -> Unit,
    onFadePauseResumeChanged: (Boolean) -> Unit,
    onPersistRepeatModeChanged: (Boolean) -> Unit,
    onPreferredRepeatModeChanged: (RepeatMode) -> Unit,
    onRememberBrowserLocationChanged: (Boolean) -> Unit,
    onShowParentDirectoryEntryChanged: (Boolean) -> Unit,
    onShowFileIconChipBackgroundChanged: (Boolean) -> Unit,
    onBrowserNameSortModeChanged: (BrowserNameSortMode) -> Unit,
    onLastBrowserLocationIdChanged: (String?) -> Unit,
    onLastBrowserDirectoryPathChanged: (String?) -> Unit,
    onRecentFoldersLimitChanged: (Int) -> Unit,
    onRecentFilesLimitChanged: (Int) -> Unit,
    onRecentFoldersChanged: (List<RecentPathEntry>) -> Unit,
    onRecentPlayedFilesChanged: (List<RecentPathEntry>) -> Unit,
    onKeepScreenOnChanged: (Boolean) -> Unit,
    onPlayerArtworkCornerRadiusDpChanged: (Int) -> Unit,
    onShowAudioOutputRouteChipChanged: (Boolean) -> Unit,
    onFilenameDisplayModeChanged: (FilenameDisplayMode) -> Unit,
    onFilenameOnlyWhenTitleMissingChanged: (Boolean) -> Unit,
    onUnknownTrackDurationSecondsChanged: (Int) -> Unit,
    onEndFadeApplyToAllTracksChanged: (Boolean) -> Unit,
    onEndFadeDurationMsChanged: (Int) -> Unit,
    onEndFadeCurveChanged: (EndFadeCurve) -> Unit,
    onVisualizationModeChanged: (VisualizationMode) -> Unit,
    onEnabledVisualizationModesChanged: (Set<VisualizationMode>) -> Unit,
    onVisualizationPerformanceModeChanged: (VisualizationPerformanceMode) -> Unit,
    onVisualizationShowDebugInfoChanged: (Boolean) -> Unit,
    onVisualizationKeepScreenOnChanged: (Boolean) -> Unit,
    onVisualizationBarCountChanged: (Int) -> Unit,
    onVisualizationBarSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationBarRoundnessDpChanged: (Int) -> Unit,
    onVisualizationBarOverlayArtworkChanged: (Boolean) -> Unit,
    onVisualizationBarUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationBarRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    onVisualizationOscStereoChanged: (Boolean) -> Unit,
    onVisualizationVuAnchorChanged: (VisualizationVuAnchor) -> Unit,
    onVisualizationVuUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationVuSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationVuRenderBackendChanged: (VisualizationRenderBackend) -> Unit
) {
    clearAllSettingsFromMainAction(
        context = context,
        prefs = prefs,
        defaultScopeTextSizeSp = defaultScopeTextSizeSp,
        selectableVisualizationModes = selectableVisualizationModes,
        onThemeModeChanged = onThemeModeChanged,
        onUseMonetChanged = onUseMonetChanged,
        pluginCoreState = buildSettingsPluginCoreStateFromStateHolders(
            settingsStates = settingsStates,
            ffmpegCapabilities = 0,
            openMptCapabilities = 0,
            vgmPlayCapabilities = 0
        ),
        pluginCoreActions = buildSettingsPluginCoreActionsFromStateHolders(settingsStates),
        onAutoPlayOnTrackSelectChanged = onAutoPlayOnTrackSelectChanged,
        onOpenPlayerOnTrackSelectChanged = onOpenPlayerOnTrackSelectChanged,
        onAutoPlayNextTrackOnEndChanged = onAutoPlayNextTrackOnEndChanged,
        onPreloadNextCachedRemoteTrackChanged = onPreloadNextCachedRemoteTrackChanged,
        onPlaylistWrapNavigationChanged = onPlaylistWrapNavigationChanged,
        onPreviousRestartsAfterThresholdChanged = onPreviousRestartsAfterThresholdChanged,
        onFadePauseResumeChanged = onFadePauseResumeChanged,
        onRespondHeadphoneMediaButtonsChanged = { settingsStates.respondHeadphoneMediaButtons.value = it },
        onPauseOnHeadphoneDisconnectChanged = { settingsStates.pauseOnHeadphoneDisconnect.value = it },
        onAudioBackendPreferenceChanged = { settingsStates.audioBackendPreference.value = it },
        onAudioPerformanceModeChanged = { settingsStates.audioPerformanceMode.value = it },
        onAudioBufferPresetChanged = { settingsStates.audioBufferPreset.value = it },
        onAudioResamplerPreferenceChanged = { settingsStates.audioResamplerPreference.value = it },
        onAudioOutputLimiterEnabledChanged = { settingsStates.audioOutputLimiterEnabled.value = it },
        onLookaheadClipperModeChanged = { settingsStates.lookaheadClipperMode.value = it },
        onAudioAllowBackendFallbackChanged = { settingsStates.audioAllowBackendFallback.value = it },
        onOpenPlayerFromNotificationChanged = { settingsStates.openPlayerFromNotification.value = it },
        onPersistRepeatModeChanged = onPersistRepeatModeChanged,
        onPreferredRepeatModeChanged = onPreferredRepeatModeChanged,
        onRememberBrowserLocationChanged = onRememberBrowserLocationChanged,
        onShowParentDirectoryEntryChanged = onShowParentDirectoryEntryChanged,
        onShowFileIconChipBackgroundChanged = onShowFileIconChipBackgroundChanged,
        onBrowserNameSortModeChanged = onBrowserNameSortModeChanged,
        onUrlCacheClearOnLaunchChanged = { settingsStates.urlCacheClearOnLaunch.value = it },
        onUrlCacheMaxTracksChanged = { settingsStates.urlCacheMaxTracks.intValue = it },
        onUrlCacheMaxBytesChanged = { settingsStates.urlCacheMaxBytes.longValue = it },
        onArchiveCacheClearOnLaunchChanged = { settingsStates.archiveCacheClearOnLaunch.value = it },
        onArchiveCacheMaxMountsChanged = { settingsStates.archiveCacheMaxMounts.intValue = it },
        onArchiveCacheMaxBytesChanged = { settingsStates.archiveCacheMaxBytes.longValue = it },
        onArchiveCacheMaxAgeDaysChanged = { settingsStates.archiveCacheMaxAgeDays.intValue = it },
        onLastBrowserLocationIdChanged = onLastBrowserLocationIdChanged,
        onLastBrowserDirectoryPathChanged = onLastBrowserDirectoryPathChanged,
        onRecentFoldersLimitChanged = onRecentFoldersLimitChanged,
        onRecentFilesLimitChanged = onRecentFilesLimitChanged,
        onRecentFoldersChanged = onRecentFoldersChanged,
        onRecentPlayedFilesChanged = onRecentPlayedFilesChanged,
        onKeepScreenOnChanged = onKeepScreenOnChanged,
        onPlayerArtworkCornerRadiusDpChanged = onPlayerArtworkCornerRadiusDpChanged,
        onShowAudioOutputRouteChipChanged = onShowAudioOutputRouteChipChanged,
        onFilenameDisplayModeChanged = onFilenameDisplayModeChanged,
        onFilenameOnlyWhenTitleMissingChanged = onFilenameOnlyWhenTitleMissingChanged,
        onUnknownTrackDurationSecondsChanged = onUnknownTrackDurationSecondsChanged,
        onEndFadeApplyToAllTracksChanged = onEndFadeApplyToAllTracksChanged,
        onEndFadeDurationMsChanged = onEndFadeDurationMsChanged,
        onEndFadeCurveChanged = onEndFadeCurveChanged,
        onVisualizationModeChanged = onVisualizationModeChanged,
        onEnabledVisualizationModesChanged = onEnabledVisualizationModesChanged,
        onVisualizationPerformanceModeChanged = onVisualizationPerformanceModeChanged,
        onVisualizationShowDebugInfoChanged = onVisualizationShowDebugInfoChanged,
        onVisualizationKeepScreenOnChanged = onVisualizationKeepScreenOnChanged,
        onVisualizationBarCountChanged = onVisualizationBarCountChanged,
        onVisualizationBarSmoothingPercentChanged = onVisualizationBarSmoothingPercentChanged,
        onVisualizationBarRoundnessDpChanged = onVisualizationBarRoundnessDpChanged,
        onVisualizationBarOverlayArtworkChanged = onVisualizationBarOverlayArtworkChanged,
        onVisualizationBarUseThemeColorChanged = onVisualizationBarUseThemeColorChanged,
        onVisualizationBarRenderBackendChanged = onVisualizationBarRenderBackendChanged,
        onVisualizationOscStereoChanged = onVisualizationOscStereoChanged,
        onVisualizationVuAnchorChanged = onVisualizationVuAnchorChanged,
        onVisualizationVuUseThemeColorChanged = onVisualizationVuUseThemeColorChanged,
        onVisualizationVuSmoothingPercentChanged = onVisualizationVuSmoothingPercentChanged,
        onVisualizationVuRenderBackendChanged = onVisualizationVuRenderBackendChanged
    )
}

internal fun clearAllPluginSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    settingsStates: AppNavigationSettingsStates
) {
    clearAllPluginSettingsFromMainAction(
        context = context,
        prefs = prefs,
        pluginCoreActions = buildSettingsPluginCoreActionsFromStateHolders(settingsStates)
    )
}

internal fun resetPluginSettingsUsingStateHolders(
    context: Context,
    prefs: SharedPreferences,
    pluginName: String,
    settingsStates: AppNavigationSettingsStates
) {
    resetPluginSettingsFromMainAction(
        context = context,
        prefs = prefs,
        pluginName = pluginName,
        pluginCoreActions = buildSettingsPluginCoreActionsFromStateHolders(settingsStates)
    )
}
