package com.flopster101.siliconplayer

internal fun buildSettingsScreenState(
    selectedPluginName: String?,
    autoPlayOnTrackSelect: Boolean,
    openPlayerOnTrackSelect: Boolean,
    autoPlayNextTrackOnEnd: Boolean,
    preloadNextCachedRemoteTrack: Boolean,
    playlistWrapNavigation: Boolean,
    previousRestartsAfterThreshold: Boolean,
    fadePauseResume: Boolean,
    respondHeadphoneMediaButtons: Boolean,
    pauseOnHeadphoneDisconnect: Boolean,
    audioFocusInterrupt: Boolean,
    audioDucking: Boolean,
    audioBackendPreference: AudioBackendPreference,
    audioPerformanceMode: AudioPerformanceMode,
    audioBufferPreset: AudioBufferPreset,
    audioResamplerPreference: AudioResamplerPreference,
    audioOutputLimiterEnabled: Boolean,
    lookaheadClipperMode: LookaheadClipperMode,
    audioAllowBackendFallback: Boolean,
    openPlayerFromNotification: Boolean,
    persistRepeatMode: Boolean,
    themeMode: ThemeMode,
    useMonet: Boolean,
    monetAvailable: Boolean,
    rememberBrowserLocation: Boolean,
    showParentDirectoryEntry: Boolean,
    showFileIconChipBackground: Boolean,
    sortArchivesBeforeFiles: Boolean,
    browserNameSortMode: BrowserNameSortMode,
    recentFoldersLimit: Int,
    recentFilesLimit: Int,
    pressBackTwiceToExit: Boolean,
    urlCacheClearOnLaunch: Boolean,
    urlCacheMaxTracks: Int,
    urlCacheMaxBytes: Long,
    archiveCacheClearOnLaunch: Boolean,
    archiveCacheMaxMounts: Int,
    archiveCacheMaxBytes: Long,
    archiveCacheMaxAgeDays: Int,
    cachedSourceFiles: List<CachedSourceFile>,
    keepScreenOn: Boolean,
    playerArtworkCornerRadiusDp: Int,
    showAudioOutputRouteChip: Boolean,
    filenameDisplayMode: FilenameDisplayMode,
    filenameOnlyWhenTitleMissing: Boolean,
    unknownTrackDurationSeconds: Int,
    endFadeApplyToAllTracks: Boolean,
    endFadeDurationMs: Int,
    endFadeCurve: EndFadeCurve,
    visualizationMode: VisualizationMode,
    enabledVisualizationModes: Set<VisualizationMode>,
    visualizationPerformanceMode: VisualizationPerformanceMode,
    visualizationShowDebugInfo: Boolean,
    visualizationBarCount: Int,
    visualizationBarSmoothingPercent: Int,
    visualizationBarRoundnessDp: Int,
    visualizationBarOverlayArtwork: Boolean,
    visualizationBarUseThemeColor: Boolean,
    visualizationBarRenderBackend: VisualizationRenderBackend,
    visualizationOscStereo: Boolean,
    visualizationVuAnchor: VisualizationVuAnchor,
    visualizationVuUseThemeColor: Boolean,
    visualizationVuSmoothingPercent: Int,
    visualizationVuRenderBackend: VisualizationRenderBackend,
    pluginCore: SettingsPluginCoreState
): SettingsScreenState {
    return SettingsScreenState(
        selectedPluginName = selectedPluginName,
        autoPlayOnTrackSelect = autoPlayOnTrackSelect,
        openPlayerOnTrackSelect = openPlayerOnTrackSelect,
        autoPlayNextTrackOnEnd = autoPlayNextTrackOnEnd,
        preloadNextCachedRemoteTrack = preloadNextCachedRemoteTrack,
        playlistWrapNavigation = playlistWrapNavigation,
        previousRestartsAfterThreshold = previousRestartsAfterThreshold,
        fadePauseResume = fadePauseResume,
        respondHeadphoneMediaButtons = respondHeadphoneMediaButtons,
        pauseOnHeadphoneDisconnect = pauseOnHeadphoneDisconnect,
        audioFocusInterrupt = audioFocusInterrupt,
        audioDucking = audioDucking,
        audioBackendPreference = audioBackendPreference,
        audioPerformanceMode = audioPerformanceMode,
        audioBufferPreset = audioBufferPreset,
        audioResamplerPreference = audioResamplerPreference,
        audioOutputLimiterEnabled = audioOutputLimiterEnabled,
        lookaheadClipperMode = lookaheadClipperMode,
        audioAllowBackendFallback = audioAllowBackendFallback,
        openPlayerFromNotification = openPlayerFromNotification,
        persistRepeatMode = persistRepeatMode,
        themeMode = themeMode,
        useMonet = useMonet,
        monetAvailable = monetAvailable,
        rememberBrowserLocation = rememberBrowserLocation,
        showParentDirectoryEntry = showParentDirectoryEntry,
        showFileIconChipBackground = showFileIconChipBackground,
        sortArchivesBeforeFiles = sortArchivesBeforeFiles,
        browserNameSortMode = browserNameSortMode,
        recentFoldersLimit = recentFoldersLimit,
        recentFilesLimit = recentFilesLimit,
        pressBackTwiceToExit = pressBackTwiceToExit,
        urlCacheClearOnLaunch = urlCacheClearOnLaunch,
        urlCacheMaxTracks = urlCacheMaxTracks,
        urlCacheMaxBytes = urlCacheMaxBytes,
        archiveCacheClearOnLaunch = archiveCacheClearOnLaunch,
        archiveCacheMaxMounts = archiveCacheMaxMounts,
        archiveCacheMaxBytes = archiveCacheMaxBytes,
        archiveCacheMaxAgeDays = archiveCacheMaxAgeDays,
        cachedSourceFiles = cachedSourceFiles,
        keepScreenOn = keepScreenOn,
        playerArtworkCornerRadiusDp = playerArtworkCornerRadiusDp,
        showAudioOutputRouteChip = showAudioOutputRouteChip,
        filenameDisplayMode = filenameDisplayMode,
        filenameOnlyWhenTitleMissing = filenameOnlyWhenTitleMissing,
        unknownTrackDurationSeconds = unknownTrackDurationSeconds,
        endFadeApplyToAllTracks = endFadeApplyToAllTracks,
        endFadeDurationMs = endFadeDurationMs,
        endFadeCurve = endFadeCurve,
        visualizationMode = visualizationMode,
        enabledVisualizationModes = enabledVisualizationModes,
        visualizationPerformanceMode = visualizationPerformanceMode,
        visualizationShowDebugInfo = visualizationShowDebugInfo,
        visualizationBarCount = visualizationBarCount,
        visualizationBarSmoothingPercent = visualizationBarSmoothingPercent,
        visualizationBarRoundnessDp = visualizationBarRoundnessDp,
        visualizationBarOverlayArtwork = visualizationBarOverlayArtwork,
        visualizationBarUseThemeColor = visualizationBarUseThemeColor,
        visualizationBarRenderBackend = visualizationBarRenderBackend,
        visualizationOscStereo = visualizationOscStereo,
        visualizationVuAnchor = visualizationVuAnchor,
        visualizationVuUseThemeColor = visualizationVuUseThemeColor,
        visualizationVuSmoothingPercent = visualizationVuSmoothingPercent,
        visualizationVuRenderBackend = visualizationVuRenderBackend,
        pluginCore = pluginCore
    )
}
