package com.flopster101.siliconplayer

import android.content.Context
import android.content.SharedPreferences

internal fun clearAllSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    defaultScopeTextSizeSp: Int,
    selectableVisualizationModes: List<VisualizationMode>,
    onThemeModeChanged: (ThemeMode) -> Unit,
    onUseMonetChanged: (Boolean) -> Unit,
    pluginCoreState: SettingsPluginCoreState,
    pluginCoreActions: SettingsPluginCoreActions,
    onAutoPlayOnTrackSelectChanged: (Boolean) -> Unit,
    onOpenPlayerOnTrackSelectChanged: (Boolean) -> Unit,
    onAutoPlayNextTrackOnEndChanged: (Boolean) -> Unit,
    onPreloadNextCachedRemoteTrackChanged: (Boolean) -> Unit,
    onPlaylistWrapNavigationChanged: (Boolean) -> Unit,
    onPreviousRestartsAfterThresholdChanged: (Boolean) -> Unit,
    onFadePauseResumeChanged: (Boolean) -> Unit,
    onRespondHeadphoneMediaButtonsChanged: (Boolean) -> Unit,
    onPauseOnHeadphoneDisconnectChanged: (Boolean) -> Unit,
    onAudioBackendPreferenceChanged: (AudioBackendPreference) -> Unit,
    onAudioPerformanceModeChanged: (AudioPerformanceMode) -> Unit,
    onAudioBufferPresetChanged: (AudioBufferPreset) -> Unit,
    onAudioResamplerPreferenceChanged: (AudioResamplerPreference) -> Unit,
    onAudioOutputLimiterEnabledChanged: (Boolean) -> Unit,
    onLookaheadClipperModeChanged: (LookaheadClipperMode) -> Unit,
    onAudioAllowBackendFallbackChanged: (Boolean) -> Unit,
    onOpenPlayerFromNotificationChanged: (Boolean) -> Unit,
    onPersistRepeatModeChanged: (Boolean) -> Unit,
    onPreferredRepeatModeChanged: (RepeatMode) -> Unit,
    onRememberBrowserLocationChanged: (Boolean) -> Unit,
    onShowParentDirectoryEntryChanged: (Boolean) -> Unit,
    onShowFileIconChipBackgroundChanged: (Boolean) -> Unit,
    onBrowserNameSortModeChanged: (BrowserNameSortMode) -> Unit,
    onUrlCacheClearOnLaunchChanged: (Boolean) -> Unit,
    onUrlCacheMaxTracksChanged: (Int) -> Unit,
    onUrlCacheMaxBytesChanged: (Long) -> Unit,
    onArchiveCacheClearOnLaunchChanged: (Boolean) -> Unit,
    onArchiveCacheMaxMountsChanged: (Int) -> Unit,
    onArchiveCacheMaxBytesChanged: (Long) -> Unit,
    onArchiveCacheMaxAgeDaysChanged: (Int) -> Unit,
    onLastBrowserLocationIdChanged: (String?) -> Unit,
    onLastBrowserDirectoryPathChanged: (String?) -> Unit,
    onRecentFoldersLimitChanged: (Int) -> Unit,
    onRecentFilesLimitChanged: (Int) -> Unit,
    onRecentFoldersChanged: (List<RecentPathEntry>) -> Unit,
    onRecentPlayedFilesChanged: (List<RecentPathEntry>) -> Unit,
    onKeepScreenOnChanged: (Boolean) -> Unit,
    onPlayerArtworkCornerRadiusDpChanged: (Int) -> Unit,
    onShowAudioOutputRouteChipChanged: (Boolean) -> Unit,
    onFilenameDisplayModeChanged: (FilenameDisplayMode) -> Unit,
    onFilenameOnlyWhenTitleMissingChanged: (Boolean) -> Unit,
    onUnknownTrackDurationSecondsChanged: (Int) -> Unit,
    onEndFadeApplyToAllTracksChanged: (Boolean) -> Unit,
    onEndFadeDurationMsChanged: (Int) -> Unit,
    onEndFadeCurveChanged: (EndFadeCurve) -> Unit,
    onVisualizationModeChanged: (VisualizationMode) -> Unit,
    onEnabledVisualizationModesChanged: (Set<VisualizationMode>) -> Unit,
    onVisualizationPerformanceModeChanged: (VisualizationPerformanceMode) -> Unit,
    onVisualizationShowDebugInfoChanged: (Boolean) -> Unit,
    onVisualizationKeepScreenOnChanged: (Boolean) -> Unit,
    onVisualizationBarCountChanged: (Int) -> Unit,
    onVisualizationBarSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationBarRoundnessDpChanged: (Int) -> Unit,
    onVisualizationBarOverlayArtworkChanged: (Boolean) -> Unit,
    onVisualizationBarUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationBarRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    onVisualizationOscStereoChanged: (Boolean) -> Unit,
    onVisualizationVuAnchorChanged: (VisualizationVuAnchor) -> Unit,
    onVisualizationVuUseThemeColorChanged: (Boolean) -> Unit,
    onVisualizationVuSmoothingPercentChanged: (Int) -> Unit,
    onVisualizationVuRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
) {
    clearAllSettingsAction(
        context = context,
        prefs = prefs,
        defaultScopeTextSizeSp = defaultScopeTextSizeSp,
        selectableVisualizationModes = selectableVisualizationModes,
        onThemeModeChanged = onThemeModeChanged,
        onUseMonetChanged = onUseMonetChanged,
        ffmpegCoreSampleRateHz = pluginCoreState.ffmpegSampleRateHz,
        openMptCoreSampleRateHz = pluginCoreState.openMptSampleRateHz,
        vgmPlayCoreSampleRateHz = pluginCoreState.vgmPlaySampleRateHz,
        gmeCoreSampleRateHz = pluginCoreState.gmeSampleRateHz,
        crsidCoreSampleRateHz = pluginCoreState.crsidSampleRateHz,
        sidPlayFpCoreSampleRateHz = pluginCoreState.sidPlayFpSampleRateHz,
        lazyUsf2CoreSampleRateHz = pluginCoreState.lazyUsf2SampleRateHz,
        adPlugCoreSampleRateHz = pluginCoreState.adPlugSampleRateHz,
        hivelyTrackerCoreSampleRateHz = pluginCoreState.hivelyTrackerSampleRateHz,
        klystrackCoreSampleRateHz = pluginCoreState.klystrackSampleRateHz,
        furnaceCoreSampleRateHz = pluginCoreState.furnaceSampleRateHz,
        uadeCoreSampleRateHz = pluginCoreState.uadeSampleRateHz,
        adPlugOplEngine = pluginCoreState.adPlugOplEngine,
        vio2sfInterpolationQuality = pluginCoreState.vio2sfInterpolationQuality,
        sc68SamplingRateHz = pluginCoreState.sc68SamplingRateHz,
        sc68Asid = pluginCoreState.sc68Asid,
        sc68DefaultTimeSeconds = pluginCoreState.sc68DefaultTimeSeconds,
        sc68YmEngine = pluginCoreState.sc68YmEngine,
        sc68YmVolModel = pluginCoreState.sc68YmVolModel,
        vgmPlayLoopCount = pluginCoreState.vgmPlayLoopCount,
        vgmPlayVsyncRate = pluginCoreState.vgmPlayVsyncRate,
        vgmPlayResampleMode = pluginCoreState.vgmPlayResampleMode,
        vgmPlayChipSampleMode = pluginCoreState.vgmPlayChipSampleMode,
        vgmPlayChipSampleRate = pluginCoreState.vgmPlayChipSampleRate,
        gmeTempoPercent = pluginCoreState.gmeTempoPercent,
        gmeStereoSeparationPercent = pluginCoreState.gmeStereoSeparationPercent,
        gmeEqTrebleDecibel = pluginCoreState.gmeEqTrebleDecibel,
        gmeEqBassHz = pluginCoreState.gmeEqBassHz,
        gmeSpcInterpolation = pluginCoreState.gmeSpcInterpolation,
        sidPlayFpBackend = pluginCoreState.sidPlayFpBackend,
        sidPlayFpClockMode = pluginCoreState.sidPlayFpClockMode,
        sidPlayFpSidModelMode = pluginCoreState.sidPlayFpSidModelMode,
        sidPlayFpFilterCurve6581Percent = pluginCoreState.sidPlayFpFilterCurve6581Percent,
        sidPlayFpFilterRange6581Percent = pluginCoreState.sidPlayFpFilterRange6581Percent,
        sidPlayFpFilterCurve8580Percent = pluginCoreState.sidPlayFpFilterCurve8580Percent,
        sidPlayFpReSidFpCombinedWaveformsStrength = pluginCoreState.sidPlayFpReSidFpCombinedWaveformsStrength,
        openMptStereoSeparationPercent = pluginCoreState.openMptStereoSeparationPercent,
        openMptStereoSeparationAmigaPercent = pluginCoreState.openMptStereoSeparationAmigaPercent,
        openMptInterpolationFilterLength = pluginCoreState.openMptInterpolationFilterLength,
        openMptAmigaResamplerMode = pluginCoreState.openMptAmigaResamplerMode,
        openMptVolumeRampingStrength = pluginCoreState.openMptVolumeRampingStrength,
        openMptMasterGainMilliBel = pluginCoreState.openMptMasterGainMilliBel,
        vgmPlayAllowNonLoopingLoop = pluginCoreState.vgmPlayAllowNonLoopingLoop,
        gmeEchoEnabled = pluginCoreState.gmeEchoEnabled,
        gmeAccuracyEnabled = pluginCoreState.gmeAccuracyEnabled,
        gmeSpcUseBuiltInFade = pluginCoreState.gmeSpcUseBuiltInFade,
        gmeSpcUseNativeSampleRate = pluginCoreState.gmeSpcUseNativeSampleRate,
        lazyUsf2UseHleAudio = pluginCoreState.lazyUsf2UseHleAudio,
        sc68AmigaFilter = pluginCoreState.sc68AmigaFilter,
        uadeFilterEnabled = pluginCoreState.uadeFilterEnabled,
        uadeNtscMode = pluginCoreState.uadeNtscMode,
        sidPlayFpFilter6581Enabled = pluginCoreState.sidPlayFpFilter6581Enabled,
        sidPlayFpFilter8580Enabled = pluginCoreState.sidPlayFpFilter8580Enabled,
        sidPlayFpDigiBoost8580 = pluginCoreState.sidPlayFpDigiBoost8580,
        sidPlayFpReSidFpFastSampling = pluginCoreState.sidPlayFpReSidFpFastSampling,
        openMptAmigaResamplerApplyAllModules = pluginCoreState.openMptAmigaResamplerApplyAllModules,
        openMptFt2XmVolumeRamping = pluginCoreState.openMptFt2XmVolumeRamping,
        openMptSurroundEnabled = pluginCoreState.openMptSurroundEnabled,
        sc68AmigaBlend = pluginCoreState.sc68AmigaBlend,
        sc68AmigaClock = pluginCoreState.sc68AmigaClock,
        uadePanningMode = pluginCoreState.uadePanningMode,
        hivelyTrackerPanningMode = pluginCoreState.hivelyTrackerPanningMode,
        hivelyTrackerMixGainPercent = pluginCoreState.hivelyTrackerMixGainPercent,
        klystrackPlayerQuality = pluginCoreState.klystrackPlayerQuality,
        furnaceYm2612Core = pluginCoreState.furnaceYm2612Core,
        furnaceSnCore = pluginCoreState.furnaceSnCore,
        furnaceNesCore = pluginCoreState.furnaceNesCore,
        furnaceC64Core = pluginCoreState.furnaceC64Core,
        furnaceGbQuality = pluginCoreState.furnaceGbQuality,
        furnaceDsidQuality = pluginCoreState.furnaceDsidQuality,
        furnaceAyCore = pluginCoreState.furnaceAyCore,
        crsidClockMode = pluginCoreState.crsidClockMode,
        crsidSidModelMode = pluginCoreState.crsidSidModelMode,
        crsidQualityMode = pluginCoreState.crsidQualityMode,
        crsidFilter6581Preset = pluginCoreState.crsidFilter6581Preset,
        vgmPlayChipCoreSelections = pluginCoreState.vgmPlayChipCoreSelections,
        onAutoPlayOnTrackSelectChanged = onAutoPlayOnTrackSelectChanged,
        onOpenPlayerOnTrackSelectChanged = onOpenPlayerOnTrackSelectChanged,
        onAutoPlayNextTrackOnEndChanged = onAutoPlayNextTrackOnEndChanged,
        onPreloadNextCachedRemoteTrackChanged = onPreloadNextCachedRemoteTrackChanged,
        onPlaylistWrapNavigationChanged = onPlaylistWrapNavigationChanged,
        onPreviousRestartsAfterThresholdChanged = onPreviousRestartsAfterThresholdChanged,
        onFadePauseResumeChanged = onFadePauseResumeChanged,
        onRespondHeadphoneMediaButtonsChanged = onRespondHeadphoneMediaButtonsChanged,
        onPauseOnHeadphoneDisconnectChanged = onPauseOnHeadphoneDisconnectChanged,
        onAudioBackendPreferenceChanged = onAudioBackendPreferenceChanged,
        onAudioPerformanceModeChanged = onAudioPerformanceModeChanged,
        onAudioBufferPresetChanged = onAudioBufferPresetChanged,
        onAudioResamplerPreferenceChanged = onAudioResamplerPreferenceChanged,
        onAudioOutputLimiterEnabledChanged = onAudioOutputLimiterEnabledChanged,
        onLookaheadClipperModeChanged = onLookaheadClipperModeChanged,
        onAudioAllowBackendFallbackChanged = onAudioAllowBackendFallbackChanged,
        onOpenPlayerFromNotificationChanged = onOpenPlayerFromNotificationChanged,
        onPersistRepeatModeChanged = onPersistRepeatModeChanged,
        onPreferredRepeatModeChanged = onPreferredRepeatModeChanged,
        onRememberBrowserLocationChanged = onRememberBrowserLocationChanged,
        onShowParentDirectoryEntryChanged = onShowParentDirectoryEntryChanged,
        onShowFileIconChipBackgroundChanged = onShowFileIconChipBackgroundChanged,
        onBrowserNameSortModeChanged = onBrowserNameSortModeChanged,
        onUrlCacheClearOnLaunchChanged = onUrlCacheClearOnLaunchChanged,
        onUrlCacheMaxTracksChanged = onUrlCacheMaxTracksChanged,
        onUrlCacheMaxBytesChanged = onUrlCacheMaxBytesChanged,
        onArchiveCacheClearOnLaunchChanged = onArchiveCacheClearOnLaunchChanged,
        onArchiveCacheMaxMountsChanged = onArchiveCacheMaxMountsChanged,
        onArchiveCacheMaxBytesChanged = onArchiveCacheMaxBytesChanged,
        onArchiveCacheMaxAgeDaysChanged = onArchiveCacheMaxAgeDaysChanged,
        onLastBrowserLocationIdChanged = onLastBrowserLocationIdChanged,
        onLastBrowserDirectoryPathChanged = onLastBrowserDirectoryPathChanged,
        onRecentFoldersLimitChanged = onRecentFoldersLimitChanged,
        onRecentFilesLimitChanged = onRecentFilesLimitChanged,
        onRecentFoldersChanged = onRecentFoldersChanged,
        onRecentPlayedFilesChanged = onRecentPlayedFilesChanged,
        onKeepScreenOnChanged = onKeepScreenOnChanged,
        onPlayerArtworkCornerRadiusDpChanged = onPlayerArtworkCornerRadiusDpChanged,
        onShowAudioOutputRouteChipChanged = onShowAudioOutputRouteChipChanged,
        onFilenameDisplayModeChanged = onFilenameDisplayModeChanged,
        onFilenameOnlyWhenTitleMissingChanged = onFilenameOnlyWhenTitleMissingChanged,
        onUnknownTrackDurationSecondsChanged = onUnknownTrackDurationSecondsChanged,
        onEndFadeApplyToAllTracksChanged = onEndFadeApplyToAllTracksChanged,
        onEndFadeDurationMsChanged = onEndFadeDurationMsChanged,
        onEndFadeCurveChanged = onEndFadeCurveChanged,
        onVisualizationModeChanged = onVisualizationModeChanged,
        onEnabledVisualizationModesChanged = onEnabledVisualizationModesChanged,
        onVisualizationPerformanceModeChanged = onVisualizationPerformanceModeChanged,
        onVisualizationShowDebugInfoChanged = onVisualizationShowDebugInfoChanged,
        onVisualizationKeepScreenOnChanged = onVisualizationKeepScreenOnChanged,
        onVisualizationBarCountChanged = onVisualizationBarCountChanged,
        onVisualizationBarSmoothingPercentChanged = onVisualizationBarSmoothingPercentChanged,
        onVisualizationBarRoundnessDpChanged = onVisualizationBarRoundnessDpChanged,
        onVisualizationBarOverlayArtworkChanged = onVisualizationBarOverlayArtworkChanged,
        onVisualizationBarUseThemeColorChanged = onVisualizationBarUseThemeColorChanged,
        onVisualizationBarRenderBackendChanged = onVisualizationBarRenderBackendChanged,
        onVisualizationOscStereoChanged = onVisualizationOscStereoChanged,
        onVisualizationVuAnchorChanged = onVisualizationVuAnchorChanged,
        onVisualizationVuUseThemeColorChanged = onVisualizationVuUseThemeColorChanged,
        onVisualizationVuSmoothingPercentChanged = onVisualizationVuSmoothingPercentChanged,
        onVisualizationVuRenderBackendChanged = onVisualizationVuRenderBackendChanged,
        onSc68SamplingRateHzChanged = pluginCoreActions.onSc68SamplingRateHzChanged,
        onSc68AsidChanged = pluginCoreActions.onSc68AsidChanged,
        onSc68DefaultTimeSecondsChanged = pluginCoreActions.onSc68DefaultTimeSecondsChanged,
        onSc68YmEngineChanged = pluginCoreActions.onSc68YmEngineChanged,
        onSc68YmVolModelChanged = pluginCoreActions.onSc68YmVolModelChanged,
        onSc68AmigaFilterChanged = pluginCoreActions.onSc68AmigaFilterChanged,
        onSc68AmigaBlendChanged = pluginCoreActions.onSc68AmigaBlendChanged,
        onSc68AmigaClockChanged = pluginCoreActions.onSc68AmigaClockChanged,
        onUadeCoreSampleRateHzChanged = pluginCoreActions.onUadeSampleRateChanged,
        onUadeFilterEnabledChanged = pluginCoreActions.onUadeFilterEnabledChanged,
        onUadeNtscModeChanged = pluginCoreActions.onUadeNtscModeChanged,
        onUadePanningModeChanged = pluginCoreActions.onUadePanningModeChanged,
        onHivelyTrackerCoreSampleRateHzChanged = pluginCoreActions.onHivelyTrackerSampleRateChanged,
        onKlystrackCoreSampleRateHzChanged = pluginCoreActions.onKlystrackSampleRateChanged,
        onFurnaceCoreSampleRateHzChanged = pluginCoreActions.onFurnaceSampleRateChanged,
        onHivelyTrackerPanningModeChanged = pluginCoreActions.onHivelyTrackerPanningModeChanged,
        onHivelyTrackerMixGainPercentChanged = pluginCoreActions.onHivelyTrackerMixGainPercentChanged,
        onKlystrackPlayerQualityChanged = pluginCoreActions.onKlystrackPlayerQualityChanged,
        onFurnaceYm2612CoreChanged = pluginCoreActions.onFurnaceYm2612CoreChanged,
        onFurnaceSnCoreChanged = pluginCoreActions.onFurnaceSnCoreChanged,
        onFurnaceNesCoreChanged = pluginCoreActions.onFurnaceNesCoreChanged,
        onFurnaceC64CoreChanged = pluginCoreActions.onFurnaceC64CoreChanged,
        onFurnaceGbQualityChanged = pluginCoreActions.onFurnaceGbQualityChanged,
        onFurnaceDsidQualityChanged = pluginCoreActions.onFurnaceDsidQualityChanged,
        onFurnaceAyCoreChanged = pluginCoreActions.onFurnaceAyCoreChanged,
        onAdPlugCoreSampleRateHzChanged = pluginCoreActions.onAdPlugSampleRateChanged,
        onAdPlugOplEngineChanged = pluginCoreActions.onAdPlugOplEngineChanged,
    )
}

internal fun clearAllPluginSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    pluginCoreActions: SettingsPluginCoreActions,
) {
    clearAllPluginSettingsAction(
        context = context,
        prefs = prefs,
        onFfmpegCoreSampleRateHzChanged = pluginCoreActions.onFfmpegSampleRateChanged,
        onFfmpegGaplessRepeatTrackChanged = pluginCoreActions.onFfmpegGaplessRepeatTrackChanged,
        onOpenMptCoreSampleRateHzChanged = pluginCoreActions.onOpenMptSampleRateChanged,
        onVgmPlayCoreSampleRateHzChanged = pluginCoreActions.onVgmPlaySampleRateChanged,
        onGmeCoreSampleRateHzChanged = pluginCoreActions.onGmeSampleRateChanged,
        onCrsidCoreSampleRateHzChanged = pluginCoreActions.onCrsidSampleRateChanged,
        onSidPlayFpCoreSampleRateHzChanged = pluginCoreActions.onSidPlayFpSampleRateChanged,
        onLazyUsf2CoreSampleRateHzChanged = pluginCoreActions.onLazyUsf2SampleRateChanged,
        onAdPlugCoreSampleRateHzChanged = pluginCoreActions.onAdPlugSampleRateChanged,
        onHivelyTrackerCoreSampleRateHzChanged = pluginCoreActions.onHivelyTrackerSampleRateChanged,
        onKlystrackCoreSampleRateHzChanged = pluginCoreActions.onKlystrackSampleRateChanged,
        onFurnaceCoreSampleRateHzChanged = pluginCoreActions.onFurnaceSampleRateChanged,
        onAdPlugOplEngineChanged = pluginCoreActions.onAdPlugOplEngineChanged,
        onLazyUsf2UseHleAudioChanged = pluginCoreActions.onLazyUsf2UseHleAudioChanged,
        onVio2sfInterpolationQualityChanged = pluginCoreActions.onVio2sfInterpolationQualityChanged,
        onSc68SamplingRateHzChanged = pluginCoreActions.onSc68SamplingRateHzChanged,
        onSc68AsidChanged = pluginCoreActions.onSc68AsidChanged,
        onSc68DefaultTimeSecondsChanged = pluginCoreActions.onSc68DefaultTimeSecondsChanged,
        onSc68YmEngineChanged = pluginCoreActions.onSc68YmEngineChanged,
        onSc68YmVolModelChanged = pluginCoreActions.onSc68YmVolModelChanged,
        onSc68AmigaFilterChanged = pluginCoreActions.onSc68AmigaFilterChanged,
        onSc68AmigaBlendChanged = pluginCoreActions.onSc68AmigaBlendChanged,
        onSc68AmigaClockChanged = pluginCoreActions.onSc68AmigaClockChanged,
        onUadeCoreSampleRateHzChanged = pluginCoreActions.onUadeSampleRateChanged,
        onUadeFilterEnabledChanged = pluginCoreActions.onUadeFilterEnabledChanged,
        onUadeNtscModeChanged = pluginCoreActions.onUadeNtscModeChanged,
        onUadePanningModeChanged = pluginCoreActions.onUadePanningModeChanged,
        onHivelyTrackerPanningModeChanged = pluginCoreActions.onHivelyTrackerPanningModeChanged,
        onHivelyTrackerMixGainPercentChanged = pluginCoreActions.onHivelyTrackerMixGainPercentChanged,
        onKlystrackPlayerQualityChanged = pluginCoreActions.onKlystrackPlayerQualityChanged,
        onFurnaceYm2612CoreChanged = pluginCoreActions.onFurnaceYm2612CoreChanged,
        onFurnaceSnCoreChanged = pluginCoreActions.onFurnaceSnCoreChanged,
        onFurnaceNesCoreChanged = pluginCoreActions.onFurnaceNesCoreChanged,
        onFurnaceC64CoreChanged = pluginCoreActions.onFurnaceC64CoreChanged,
        onFurnaceGbQualityChanged = pluginCoreActions.onFurnaceGbQualityChanged,
        onFurnaceDsidQualityChanged = pluginCoreActions.onFurnaceDsidQualityChanged,
        onFurnaceAyCoreChanged = pluginCoreActions.onFurnaceAyCoreChanged,
        onCrsidClockModeChanged = pluginCoreActions.onCrsidClockModeChanged,
        onCrsidSidModelModeChanged = pluginCoreActions.onCrsidSidModelModeChanged,
        onCrsidQualityModeChanged = pluginCoreActions.onCrsidQualityModeChanged,
        onCrsidFilter6581PresetChanged = pluginCoreActions.onCrsidFilter6581PresetChanged,
        onSidPlayFpBackendChanged = pluginCoreActions.onSidPlayFpBackendChanged,
        onSidPlayFpClockModeChanged = pluginCoreActions.onSidPlayFpClockModeChanged,
        onSidPlayFpSidModelModeChanged = pluginCoreActions.onSidPlayFpSidModelModeChanged,
        onSidPlayFpFilter6581EnabledChanged = pluginCoreActions.onSidPlayFpFilter6581EnabledChanged,
        onSidPlayFpFilter8580EnabledChanged = pluginCoreActions.onSidPlayFpFilter8580EnabledChanged,
        onSidPlayFpDigiBoost8580Changed = pluginCoreActions.onSidPlayFpDigiBoost8580Changed,
        onSidPlayFpFilterCurve6581PercentChanged = pluginCoreActions.onSidPlayFpFilterCurve6581PercentChanged,
        onSidPlayFpFilterRange6581PercentChanged = pluginCoreActions.onSidPlayFpFilterRange6581PercentChanged,
        onSidPlayFpFilterCurve8580PercentChanged = pluginCoreActions.onSidPlayFpFilterCurve8580PercentChanged,
        onSidPlayFpReSidFpFastSamplingChanged = pluginCoreActions.onSidPlayFpReSidFpFastSamplingChanged,
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged = pluginCoreActions.onSidPlayFpReSidFpCombinedWaveformsStrengthChanged,
        onGmeTempoPercentChanged = pluginCoreActions.onGmeTempoPercentChanged,
        onGmeStereoSeparationPercentChanged = pluginCoreActions.onGmeStereoSeparationPercentChanged,
        onGmeEchoEnabledChanged = pluginCoreActions.onGmeEchoEnabledChanged,
        onGmeAccuracyEnabledChanged = pluginCoreActions.onGmeAccuracyEnabledChanged,
        onGmeEqTrebleDecibelChanged = pluginCoreActions.onGmeEqTrebleDecibelChanged,
        onGmeEqBassHzChanged = pluginCoreActions.onGmeEqBassHzChanged,
        onGmeSpcUseBuiltInFadeChanged = pluginCoreActions.onGmeSpcUseBuiltInFadeChanged,
        onGmeSpcInterpolationChanged = pluginCoreActions.onGmeSpcInterpolationChanged,
        onGmeSpcUseNativeSampleRateChanged = pluginCoreActions.onGmeSpcUseNativeSampleRateChanged,
        onVgmPlayLoopCountChanged = pluginCoreActions.onVgmPlayLoopCountChanged,
        onVgmPlayAllowNonLoopingLoopChanged = pluginCoreActions.onVgmPlayAllowNonLoopingLoopChanged,
        onVgmPlayVsyncRateChanged = pluginCoreActions.onVgmPlayVsyncRateChanged,
        onVgmPlayResampleModeChanged = pluginCoreActions.onVgmPlayResampleModeChanged,
        onVgmPlayChipSampleModeChanged = pluginCoreActions.onVgmPlayChipSampleModeChanged,
        onVgmPlayChipSampleRateChanged = pluginCoreActions.onVgmPlayChipSampleRateChanged,
        onVgmPlayChipCoreSelectionsChanged = { chipSelections ->
            chipSelections.forEach { (chipKey, selectedValue) ->
                pluginCoreActions.onVgmPlayChipCoreChanged(chipKey, selectedValue)
            }
        },
        onOpenMptStereoSeparationPercentChanged = pluginCoreActions.onOpenMptStereoSeparationPercentChanged,
        onOpenMptStereoSeparationAmigaPercentChanged = pluginCoreActions.onOpenMptStereoSeparationAmigaPercentChanged,
        onOpenMptInterpolationFilterLengthChanged = pluginCoreActions.onOpenMptInterpolationFilterLengthChanged,
        onOpenMptAmigaResamplerModeChanged = pluginCoreActions.onOpenMptAmigaResamplerModeChanged,
        onOpenMptAmigaResamplerApplyAllModulesChanged = pluginCoreActions.onOpenMptAmigaResamplerApplyAllModulesChanged,
        onOpenMptVolumeRampingStrengthChanged = pluginCoreActions.onOpenMptVolumeRampingStrengthChanged,
        onOpenMptFt2XmVolumeRampingChanged = pluginCoreActions.onOpenMptFt2XmVolumeRampingChanged,
        onOpenMptMasterGainMilliBelChanged = pluginCoreActions.onOpenMptMasterGainMilliBelChanged,
        onOpenMptSurroundEnabledChanged = pluginCoreActions.onOpenMptSurroundEnabledChanged,
    )
}

internal fun resetPluginSettingsFromMainAction(
    context: Context,
    prefs: SharedPreferences,
    pluginName: String,
    pluginCoreActions: SettingsPluginCoreActions,
) {
    resetPluginSettingsAction(
        context = context,
        prefs = prefs,
        pluginName = pluginName,
        onFfmpegCoreSampleRateHzChanged = pluginCoreActions.onFfmpegSampleRateChanged,
        onFfmpegGaplessRepeatTrackChanged = pluginCoreActions.onFfmpegGaplessRepeatTrackChanged,
        onOpenMptCoreSampleRateHzChanged = pluginCoreActions.onOpenMptSampleRateChanged,
        onOpenMptStereoSeparationPercentChanged = pluginCoreActions.onOpenMptStereoSeparationPercentChanged,
        onOpenMptStereoSeparationAmigaPercentChanged = pluginCoreActions.onOpenMptStereoSeparationAmigaPercentChanged,
        onOpenMptInterpolationFilterLengthChanged = pluginCoreActions.onOpenMptInterpolationFilterLengthChanged,
        onOpenMptAmigaResamplerModeChanged = pluginCoreActions.onOpenMptAmigaResamplerModeChanged,
        onOpenMptAmigaResamplerApplyAllModulesChanged = pluginCoreActions.onOpenMptAmigaResamplerApplyAllModulesChanged,
        onOpenMptVolumeRampingStrengthChanged = pluginCoreActions.onOpenMptVolumeRampingStrengthChanged,
        onOpenMptFt2XmVolumeRampingChanged = pluginCoreActions.onOpenMptFt2XmVolumeRampingChanged,
        onOpenMptMasterGainMilliBelChanged = pluginCoreActions.onOpenMptMasterGainMilliBelChanged,
        onOpenMptSurroundEnabledChanged = pluginCoreActions.onOpenMptSurroundEnabledChanged,
        onVgmPlayCoreSampleRateHzChanged = pluginCoreActions.onVgmPlaySampleRateChanged,
        onVgmPlayLoopCountChanged = pluginCoreActions.onVgmPlayLoopCountChanged,
        onVgmPlayAllowNonLoopingLoopChanged = pluginCoreActions.onVgmPlayAllowNonLoopingLoopChanged,
        onVgmPlayVsyncRateChanged = pluginCoreActions.onVgmPlayVsyncRateChanged,
        onVgmPlayResampleModeChanged = pluginCoreActions.onVgmPlayResampleModeChanged,
        onVgmPlayChipSampleModeChanged = pluginCoreActions.onVgmPlayChipSampleModeChanged,
        onVgmPlayChipSampleRateChanged = pluginCoreActions.onVgmPlayChipSampleRateChanged,
        onVgmPlayChipCoreSelectionsChanged = { chipSelections ->
            chipSelections.forEach { (chipKey, selectedValue) ->
                pluginCoreActions.onVgmPlayChipCoreChanged(chipKey, selectedValue)
            }
        },
        onGmeCoreSampleRateHzChanged = pluginCoreActions.onGmeSampleRateChanged,
        onGmeTempoPercentChanged = pluginCoreActions.onGmeTempoPercentChanged,
        onGmeStereoSeparationPercentChanged = pluginCoreActions.onGmeStereoSeparationPercentChanged,
        onGmeEchoEnabledChanged = pluginCoreActions.onGmeEchoEnabledChanged,
        onGmeAccuracyEnabledChanged = pluginCoreActions.onGmeAccuracyEnabledChanged,
        onGmeEqTrebleDecibelChanged = pluginCoreActions.onGmeEqTrebleDecibelChanged,
        onGmeEqBassHzChanged = pluginCoreActions.onGmeEqBassHzChanged,
        onGmeSpcUseBuiltInFadeChanged = pluginCoreActions.onGmeSpcUseBuiltInFadeChanged,
        onGmeSpcInterpolationChanged = pluginCoreActions.onGmeSpcInterpolationChanged,
        onGmeSpcUseNativeSampleRateChanged = pluginCoreActions.onGmeSpcUseNativeSampleRateChanged,
        onCrsidCoreSampleRateHzChanged = pluginCoreActions.onCrsidSampleRateChanged,
        onLazyUsf2CoreSampleRateHzChanged = pluginCoreActions.onLazyUsf2SampleRateChanged,
        onAdPlugCoreSampleRateHzChanged = pluginCoreActions.onAdPlugSampleRateChanged,
        onHivelyTrackerCoreSampleRateHzChanged = pluginCoreActions.onHivelyTrackerSampleRateChanged,
        onKlystrackCoreSampleRateHzChanged = pluginCoreActions.onKlystrackSampleRateChanged,
        onFurnaceCoreSampleRateHzChanged = pluginCoreActions.onFurnaceSampleRateChanged,
        onAdPlugOplEngineChanged = pluginCoreActions.onAdPlugOplEngineChanged,
        onLazyUsf2UseHleAudioChanged = pluginCoreActions.onLazyUsf2UseHleAudioChanged,
        onVio2sfInterpolationQualityChanged = pluginCoreActions.onVio2sfInterpolationQualityChanged,
        onSc68SamplingRateHzChanged = pluginCoreActions.onSc68SamplingRateHzChanged,
        onSc68AsidChanged = pluginCoreActions.onSc68AsidChanged,
        onSc68DefaultTimeSecondsChanged = pluginCoreActions.onSc68DefaultTimeSecondsChanged,
        onSc68YmEngineChanged = pluginCoreActions.onSc68YmEngineChanged,
        onSc68YmVolModelChanged = pluginCoreActions.onSc68YmVolModelChanged,
        onSc68AmigaFilterChanged = pluginCoreActions.onSc68AmigaFilterChanged,
        onSc68AmigaBlendChanged = pluginCoreActions.onSc68AmigaBlendChanged,
        onSc68AmigaClockChanged = pluginCoreActions.onSc68AmigaClockChanged,
        onUadeCoreSampleRateHzChanged = pluginCoreActions.onUadeSampleRateChanged,
        onUadeFilterEnabledChanged = pluginCoreActions.onUadeFilterEnabledChanged,
        onUadeNtscModeChanged = pluginCoreActions.onUadeNtscModeChanged,
        onUadePanningModeChanged = pluginCoreActions.onUadePanningModeChanged,
        onHivelyTrackerPanningModeChanged = pluginCoreActions.onHivelyTrackerPanningModeChanged,
        onHivelyTrackerMixGainPercentChanged = pluginCoreActions.onHivelyTrackerMixGainPercentChanged,
        onKlystrackPlayerQualityChanged = pluginCoreActions.onKlystrackPlayerQualityChanged,
        onFurnaceYm2612CoreChanged = pluginCoreActions.onFurnaceYm2612CoreChanged,
        onFurnaceSnCoreChanged = pluginCoreActions.onFurnaceSnCoreChanged,
        onFurnaceNesCoreChanged = pluginCoreActions.onFurnaceNesCoreChanged,
        onFurnaceC64CoreChanged = pluginCoreActions.onFurnaceC64CoreChanged,
        onFurnaceGbQualityChanged = pluginCoreActions.onFurnaceGbQualityChanged,
        onFurnaceDsidQualityChanged = pluginCoreActions.onFurnaceDsidQualityChanged,
        onFurnaceAyCoreChanged = pluginCoreActions.onFurnaceAyCoreChanged,
        onCrsidClockModeChanged = pluginCoreActions.onCrsidClockModeChanged,
        onCrsidSidModelModeChanged = pluginCoreActions.onCrsidSidModelModeChanged,
        onCrsidQualityModeChanged = pluginCoreActions.onCrsidQualityModeChanged,
        onCrsidFilter6581PresetChanged = pluginCoreActions.onCrsidFilter6581PresetChanged,
        onSidPlayFpCoreSampleRateHzChanged = pluginCoreActions.onSidPlayFpSampleRateChanged,
        onSidPlayFpBackendChanged = pluginCoreActions.onSidPlayFpBackendChanged,
        onSidPlayFpClockModeChanged = pluginCoreActions.onSidPlayFpClockModeChanged,
        onSidPlayFpSidModelModeChanged = pluginCoreActions.onSidPlayFpSidModelModeChanged,
        onSidPlayFpFilter6581EnabledChanged = pluginCoreActions.onSidPlayFpFilter6581EnabledChanged,
        onSidPlayFpFilter8580EnabledChanged = pluginCoreActions.onSidPlayFpFilter8580EnabledChanged,
        onSidPlayFpDigiBoost8580Changed = pluginCoreActions.onSidPlayFpDigiBoost8580Changed,
        onSidPlayFpFilterCurve6581PercentChanged = pluginCoreActions.onSidPlayFpFilterCurve6581PercentChanged,
        onSidPlayFpFilterRange6581PercentChanged = pluginCoreActions.onSidPlayFpFilterRange6581PercentChanged,
        onSidPlayFpFilterCurve8580PercentChanged = pluginCoreActions.onSidPlayFpFilterCurve8580PercentChanged,
        onSidPlayFpReSidFpFastSamplingChanged = pluginCoreActions.onSidPlayFpReSidFpFastSamplingChanged,
        onSidPlayFpReSidFpCombinedWaveformsStrengthChanged =
            pluginCoreActions.onSidPlayFpReSidFpCombinedWaveformsStrengthChanged,
    )
}
