package com.flopster101.siliconplayer

internal data class SettingsPluginCoreState(
    val ffmpegSampleRateHz: Int,
    val ffmpegGaplessRepeatTrack: Boolean,
    val ffmpegCapabilities: Int,
    val openMptSampleRateHz: Int,
    val openMptCapabilities: Int,
    val vgmPlaySampleRateHz: Int,
    val vgmPlayCapabilities: Int,
    val gmeSampleRateHz: Int,
    val crsidSampleRateHz: Int,
    val sidPlayFpSampleRateHz: Int,
    val lazyUsf2SampleRateHz: Int,
    val adPlugSampleRateHz: Int,
    val hivelyTrackerSampleRateHz: Int,
    val klystrackSampleRateHz: Int,
    val furnaceSampleRateHz: Int,
    val uadeSampleRateHz: Int,
    val adPlugOplEngine: Int,
    val lazyUsf2UseHleAudio: Boolean,
    val vio2sfInterpolationQuality: Int,
    val sc68SamplingRateHz: Int,
    val sc68Asid: Int,
    val sc68DefaultTimeSeconds: Int,
    val sc68YmEngine: Int,
    val sc68YmVolModel: Int,
    val sc68AmigaFilter: Boolean,
    val sc68AmigaBlend: Int,
    val sc68AmigaClock: Int,
    val uadeFilterEnabled: Boolean,
    val uadeNtscMode: Boolean,
    val uadePanningMode: Int,
    val hivelyTrackerPanningMode: Int,
    val hivelyTrackerMixGainPercent: Int,
    val klystrackPlayerQuality: Int,
    val furnaceYm2612Core: Int,
    val furnaceSnCore: Int,
    val furnaceNesCore: Int,
    val furnaceC64Core: Int,
    val furnaceGbQuality: Int,
    val furnaceDsidQuality: Int,
    val furnaceAyCore: Int,
    val crsidClockMode: Int,
    val crsidSidModelMode: Int,
    val crsidQualityMode: Int,
    val crsidFilter6581Preset: Int,
    val sidPlayFpBackend: Int,
    val sidPlayFpClockMode: Int,
    val sidPlayFpSidModelMode: Int,
    val sidPlayFpFilter6581Enabled: Boolean,
    val sidPlayFpFilter8580Enabled: Boolean,
    val sidPlayFpDigiBoost8580: Boolean,
    val sidPlayFpFilterCurve6581Percent: Int,
    val sidPlayFpFilterRange6581Percent: Int,
    val sidPlayFpFilterCurve8580Percent: Int,
    val sidPlayFpReSidFpFastSampling: Boolean,
    val sidPlayFpReSidFpCombinedWaveformsStrength: Int,
    val gmeTempoPercent: Int,
    val gmeStereoSeparationPercent: Int,
    val gmeEchoEnabled: Boolean,
    val gmeAccuracyEnabled: Boolean,
    val gmeEqTrebleDecibel: Int,
    val gmeEqBassHz: Int,
    val gmeSpcUseBuiltInFade: Boolean,
    val gmeSpcInterpolation: Int,
    val gmeSpcUseNativeSampleRate: Boolean,
    val vgmPlayLoopCount: Int,
    val vgmPlayAllowNonLoopingLoop: Boolean,
    val vgmPlayVsyncRate: Int,
    val vgmPlayResampleMode: Int,
    val vgmPlayChipSampleMode: Int,
    val vgmPlayChipSampleRate: Int,
    val vgmPlayChipCoreSelections: Map<String, Int>,
    val openMptStereoSeparationPercent: Int,
    val openMptStereoSeparationAmigaPercent: Int,
    val openMptInterpolationFilterLength: Int,
    val openMptAmigaResamplerMode: Int,
    val openMptAmigaResamplerApplyAllModules: Boolean,
    val openMptVolumeRampingStrength: Int,
    val openMptFt2XmVolumeRamping: Boolean,
    val openMptMasterGainMilliBel: Int,
    val openMptSurroundEnabled: Boolean
)

internal data class SettingsPluginCoreActions(
    val onOpenVgmPlayChipSettings: () -> Unit,
    val onPluginSelected: (String) -> Unit,
    val onPluginEnabledChanged: (String, Boolean) -> Unit,
    val onPluginPriorityChanged: (String, Int) -> Unit,
    val onPluginPriorityOrderChanged: (List<String>) -> Unit,
    val onPluginExtensionsChanged: (String, Array<String>) -> Unit,
    val onFfmpegSampleRateChanged: (Int) -> Unit,
    val onFfmpegGaplessRepeatTrackChanged: (Boolean) -> Unit,
    val onOpenMptSampleRateChanged: (Int) -> Unit,
    val onVgmPlaySampleRateChanged: (Int) -> Unit,
    val onGmeSampleRateChanged: (Int) -> Unit,
    val onCrsidSampleRateChanged: (Int) -> Unit,
    val onSidPlayFpSampleRateChanged: (Int) -> Unit,
    val onLazyUsf2SampleRateChanged: (Int) -> Unit,
    val onAdPlugSampleRateChanged: (Int) -> Unit,
    val onHivelyTrackerSampleRateChanged: (Int) -> Unit,
    val onKlystrackSampleRateChanged: (Int) -> Unit,
    val onFurnaceSampleRateChanged: (Int) -> Unit,
    val onUadeSampleRateChanged: (Int) -> Unit,
    val onAdPlugOplEngineChanged: (Int) -> Unit,
    val onLazyUsf2UseHleAudioChanged: (Boolean) -> Unit,
    val onVio2sfInterpolationQualityChanged: (Int) -> Unit,
    val onSc68SamplingRateHzChanged: (Int) -> Unit,
    val onSc68AsidChanged: (Int) -> Unit,
    val onSc68DefaultTimeSecondsChanged: (Int) -> Unit,
    val onSc68YmEngineChanged: (Int) -> Unit,
    val onSc68YmVolModelChanged: (Int) -> Unit,
    val onSc68AmigaFilterChanged: (Boolean) -> Unit,
    val onSc68AmigaBlendChanged: (Int) -> Unit,
    val onSc68AmigaClockChanged: (Int) -> Unit,
    val onUadeFilterEnabledChanged: (Boolean) -> Unit,
    val onUadeNtscModeChanged: (Boolean) -> Unit,
    val onUadePanningModeChanged: (Int) -> Unit,
    val onHivelyTrackerPanningModeChanged: (Int) -> Unit,
    val onHivelyTrackerMixGainPercentChanged: (Int) -> Unit,
    val onKlystrackPlayerQualityChanged: (Int) -> Unit,
    val onFurnaceYm2612CoreChanged: (Int) -> Unit,
    val onFurnaceSnCoreChanged: (Int) -> Unit,
    val onFurnaceNesCoreChanged: (Int) -> Unit,
    val onFurnaceC64CoreChanged: (Int) -> Unit,
    val onFurnaceGbQualityChanged: (Int) -> Unit,
    val onFurnaceDsidQualityChanged: (Int) -> Unit,
    val onFurnaceAyCoreChanged: (Int) -> Unit,
    val onCrsidClockModeChanged: (Int) -> Unit,
    val onCrsidSidModelModeChanged: (Int) -> Unit,
    val onCrsidQualityModeChanged: (Int) -> Unit,
    val onCrsidFilter6581PresetChanged: (Int) -> Unit,
    val onSidPlayFpBackendChanged: (Int) -> Unit,
    val onSidPlayFpClockModeChanged: (Int) -> Unit,
    val onSidPlayFpSidModelModeChanged: (Int) -> Unit,
    val onSidPlayFpFilter6581EnabledChanged: (Boolean) -> Unit,
    val onSidPlayFpFilter8580EnabledChanged: (Boolean) -> Unit,
    val onSidPlayFpDigiBoost8580Changed: (Boolean) -> Unit,
    val onSidPlayFpFilterCurve6581PercentChanged: (Int) -> Unit,
    val onSidPlayFpFilterRange6581PercentChanged: (Int) -> Unit,
    val onSidPlayFpFilterCurve8580PercentChanged: (Int) -> Unit,
    val onSidPlayFpReSidFpFastSamplingChanged: (Boolean) -> Unit,
    val onSidPlayFpReSidFpCombinedWaveformsStrengthChanged: (Int) -> Unit,
    val onGmeTempoPercentChanged: (Int) -> Unit,
    val onGmeStereoSeparationPercentChanged: (Int) -> Unit,
    val onGmeEchoEnabledChanged: (Boolean) -> Unit,
    val onGmeAccuracyEnabledChanged: (Boolean) -> Unit,
    val onGmeEqTrebleDecibelChanged: (Int) -> Unit,
    val onGmeEqBassHzChanged: (Int) -> Unit,
    val onGmeSpcUseBuiltInFadeChanged: (Boolean) -> Unit,
    val onGmeSpcInterpolationChanged: (Int) -> Unit,
    val onGmeSpcUseNativeSampleRateChanged: (Boolean) -> Unit,
    val onVgmPlayLoopCountChanged: (Int) -> Unit,
    val onVgmPlayAllowNonLoopingLoopChanged: (Boolean) -> Unit,
    val onVgmPlayVsyncRateChanged: (Int) -> Unit,
    val onVgmPlayResampleModeChanged: (Int) -> Unit,
    val onVgmPlayChipSampleModeChanged: (Int) -> Unit,
    val onVgmPlayChipSampleRateChanged: (Int) -> Unit,
    val onVgmPlayChipCoreChanged: (String, Int) -> Unit,
    val onOpenMptStereoSeparationPercentChanged: (Int) -> Unit,
    val onOpenMptStereoSeparationAmigaPercentChanged: (Int) -> Unit,
    val onOpenMptInterpolationFilterLengthChanged: (Int) -> Unit,
    val onOpenMptAmigaResamplerModeChanged: (Int) -> Unit,
    val onOpenMptAmigaResamplerApplyAllModulesChanged: (Boolean) -> Unit,
    val onOpenMptVolumeRampingStrengthChanged: (Int) -> Unit,
    val onOpenMptFt2XmVolumeRampingChanged: (Boolean) -> Unit,
    val onOpenMptMasterGainMilliBelChanged: (Int) -> Unit,
    val onOpenMptSurroundEnabledChanged: (Boolean) -> Unit
)

internal data class SettingsScreenState(
    val selectedPluginName: String?,
    val autoPlayOnTrackSelect: Boolean,
    val openPlayerOnTrackSelect: Boolean,
    val autoPlayNextTrackOnEnd: Boolean,
    val preloadNextCachedRemoteTrack: Boolean,
    val playlistWrapNavigation: Boolean,
    val previousRestartsAfterThreshold: Boolean,
    val fadePauseResume: Boolean,
    val respondHeadphoneMediaButtons: Boolean,
    val pauseOnHeadphoneDisconnect: Boolean,
    val audioFocusInterrupt: Boolean,
    val audioDucking: Boolean,
    val audioBackendPreference: AudioBackendPreference,
    val audioPerformanceMode: AudioPerformanceMode,
    val audioBufferPreset: AudioBufferPreset,
    val audioResamplerPreference: AudioResamplerPreference,
    val audioOutputLimiterEnabled: Boolean,
    val lookaheadClipperMode: LookaheadClipperMode,
    val audioAllowBackendFallback: Boolean,
    val openPlayerFromNotification: Boolean,
    val persistRepeatMode: Boolean,
    val themeMode: ThemeMode,
    val useMonet: Boolean,
    val monetAvailable: Boolean,
    val rememberBrowserLocation: Boolean,
    val showParentDirectoryEntry: Boolean,
    val showFileIconChipBackground: Boolean,
    val sortArchivesBeforeFiles: Boolean,
    val browserNameSortMode: BrowserNameSortMode,
    val recentFoldersLimit: Int,
    val recentFilesLimit: Int,
    val pressBackTwiceToExit: Boolean,
    val urlCacheClearOnLaunch: Boolean,
    val urlCacheMaxTracks: Int,
    val urlCacheMaxBytes: Long,
    val archiveCacheClearOnLaunch: Boolean,
    val archiveCacheMaxMounts: Int,
    val archiveCacheMaxBytes: Long,
    val archiveCacheMaxAgeDays: Int,
    val cachedSourceFiles: List<CachedSourceFile>,
    val keepScreenOn: Boolean,
    val playerArtworkCornerRadiusDp: Int,
    val showAudioOutputRouteChip: Boolean,
    val filenameDisplayMode: FilenameDisplayMode,
    val filenameOnlyWhenTitleMissing: Boolean,
    val unknownTrackDurationSeconds: Int,
    val endFadeApplyToAllTracks: Boolean,
    val endFadeDurationMs: Int,
    val endFadeCurve: EndFadeCurve,
    val visualizationMode: VisualizationMode,
    val enabledVisualizationModes: Set<VisualizationMode>,
    val visualizationPerformanceMode: VisualizationPerformanceMode,
    val visualizationShowDebugInfo: Boolean,
    val visualizationKeepScreenOn: Boolean,
    val visualizationBarCount: Int,
    val visualizationBarSmoothingPercent: Int,
    val visualizationBarRoundnessDp: Int,
    val visualizationBarOverlayArtwork: Boolean,
    val visualizationBarUseThemeColor: Boolean,
    val visualizationBarRenderBackend: VisualizationRenderBackend,
    val visualizationOscStereo: Boolean,
    val visualizationVuAnchor: VisualizationVuAnchor,
    val visualizationVuUseThemeColor: Boolean,
    val visualizationVuSmoothingPercent: Int,
    val visualizationVuRenderBackend: VisualizationRenderBackend,
    val pluginCore: SettingsPluginCoreState
)

internal data class SettingsScreenActions(
    val onBack: () -> Unit,
    val onOpenAudioPlugins: () -> Unit,
    val onOpenGeneralAudio: () -> Unit,
    val onOpenHome: () -> Unit,
    val onOpenFileBrowser: () -> Unit,
    val onOpenNetwork: () -> Unit,
    val onOpenAudioEffects: () -> Unit,
    val onClearAllAudioParameters: () -> Unit,
    val onClearPluginAudioParameters: () -> Unit,
    val onClearSongAudioParameters: () -> Unit,
    val onOpenPlayer: () -> Unit,
    val onOpenVisualization: () -> Unit,
    val onOpenVisualizationBasic: () -> Unit,
    val onOpenVisualizationBasicBars: () -> Unit,
    val onOpenVisualizationBasicOscilloscope: () -> Unit,
    val onOpenVisualizationBasicVuMeters: () -> Unit,
    val onOpenVisualizationAdvanced: () -> Unit,
    val onOpenVisualizationAdvancedChannelScope: () -> Unit,
    val onOpenVisualizationAdvancedProjectM: () -> Unit,
    val onOpenVisualizationProjectMPacks: () -> Unit,
    val onOpenMisc: () -> Unit,
    val onOpenUrlCache: () -> Unit,
    val onOpenCacheManager: () -> Unit,
    val onOpenUi: () -> Unit,
    val onOpenAbout: () -> Unit,
    val pluginCoreActions: SettingsPluginCoreActions,
    val onAutoPlayOnTrackSelectChanged: (Boolean) -> Unit,
    val onOpenPlayerOnTrackSelectChanged: (Boolean) -> Unit,
    val onAutoPlayNextTrackOnEndChanged: (Boolean) -> Unit,
    val onPreloadNextCachedRemoteTrackChanged: (Boolean) -> Unit,
    val onPlaylistWrapNavigationChanged: (Boolean) -> Unit,
    val onPreviousRestartsAfterThresholdChanged: (Boolean) -> Unit,
    val onFadePauseResumeChanged: (Boolean) -> Unit,
    val onRespondHeadphoneMediaButtonsChanged: (Boolean) -> Unit,
    val onPauseOnHeadphoneDisconnectChanged: (Boolean) -> Unit,
    val onAudioFocusInterruptChanged: (Boolean) -> Unit,
    val onAudioDuckingChanged: (Boolean) -> Unit,
    val onAudioBackendPreferenceChanged: (AudioBackendPreference) -> Unit,
    val onAudioPerformanceModeChanged: (AudioPerformanceMode) -> Unit,
    val onAudioBufferPresetChanged: (AudioBufferPreset) -> Unit,
    val onAudioResamplerPreferenceChanged: (AudioResamplerPreference) -> Unit,
    val onAudioOutputLimiterEnabledChanged: (Boolean) -> Unit,
    val onLookaheadClipperModeChanged: (LookaheadClipperMode) -> Unit,
    val onAudioAllowBackendFallbackChanged: (Boolean) -> Unit,
    val onOpenPlayerFromNotificationChanged: (Boolean) -> Unit,
    val onPersistRepeatModeChanged: (Boolean) -> Unit,
    val onThemeModeChanged: (ThemeMode) -> Unit,
    val onUseMonetChanged: (Boolean) -> Unit,
    val onRememberBrowserLocationChanged: (Boolean) -> Unit,
    val onShowParentDirectoryEntryChanged: (Boolean) -> Unit,
    val onShowFileIconChipBackgroundChanged: (Boolean) -> Unit,
    val onSortArchivesBeforeFilesChanged: (Boolean) -> Unit,
    val onBrowserNameSortModeChanged: (BrowserNameSortMode) -> Unit,
    val onRecentFoldersLimitChanged: (Int) -> Unit,
    val onRecentFilesLimitChanged: (Int) -> Unit,
    val onPressBackTwiceToExitChanged: (Boolean) -> Unit,
    val onUrlCacheClearOnLaunchChanged: (Boolean) -> Unit,
    val onUrlCacheMaxTracksChanged: (Int) -> Unit,
    val onUrlCacheMaxBytesChanged: (Long) -> Unit,
    val onArchiveCacheClearOnLaunchChanged: (Boolean) -> Unit,
    val onArchiveCacheMaxMountsChanged: (Int) -> Unit,
    val onArchiveCacheMaxBytesChanged: (Long) -> Unit,
    val onArchiveCacheMaxAgeDaysChanged: (Int) -> Unit,
    val onClearUrlCacheNow: () -> Unit,
    val onClearArchiveCacheNow: () -> Unit,
    val onRefreshCachedSourceFiles: () -> Unit,
    val onDeleteCachedSourceFiles: (List<String>) -> Unit,
    val onExportCachedSourceFiles: (List<String>) -> Unit,
    val onKeepScreenOnChanged: (Boolean) -> Unit,
    val onPlayerArtworkCornerRadiusDpChanged: (Int) -> Unit,
    val onShowAudioOutputRouteChipChanged: (Boolean) -> Unit,
    val onFilenameDisplayModeChanged: (FilenameDisplayMode) -> Unit,
    val onFilenameOnlyWhenTitleMissingChanged: (Boolean) -> Unit,
    val onUnknownTrackDurationSecondsChanged: (Int) -> Unit,
    val onEndFadeApplyToAllTracksChanged: (Boolean) -> Unit,
    val onEndFadeDurationMsChanged: (Int) -> Unit,
    val onEndFadeCurveChanged: (EndFadeCurve) -> Unit,
    val onVisualizationModeChanged: (VisualizationMode) -> Unit,
    val onEnabledVisualizationModesChanged: (Set<VisualizationMode>) -> Unit,
    val onVisualizationPerformanceModeChanged: (VisualizationPerformanceMode) -> Unit,
    val onVisualizationShowDebugInfoChanged: (Boolean) -> Unit,
    val onVisualizationKeepScreenOnChanged: (Boolean) -> Unit,
    val onVisualizationBarCountChanged: (Int) -> Unit,
    val onVisualizationBarSmoothingPercentChanged: (Int) -> Unit,
    val onVisualizationBarRoundnessDpChanged: (Int) -> Unit,
    val onVisualizationBarOverlayArtworkChanged: (Boolean) -> Unit,
    val onVisualizationBarUseThemeColorChanged: (Boolean) -> Unit,
    val onVisualizationBarRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    val onVisualizationOscStereoChanged: (Boolean) -> Unit,
    val onVisualizationVuAnchorChanged: (VisualizationVuAnchor) -> Unit,
    val onVisualizationVuUseThemeColorChanged: (Boolean) -> Unit,
    val onVisualizationVuSmoothingPercentChanged: (Int) -> Unit,
    val onVisualizationVuRenderBackendChanged: (VisualizationRenderBackend) -> Unit,
    val onResetVisualizationBarsSettings: () -> Unit,
    val onResetVisualizationOscilloscopeSettings: () -> Unit,
    val onResetVisualizationVuSettings: () -> Unit,
    val onResetVisualizationChannelScopeSettings: () -> Unit,
    val onResetVisualizationProjectMSettings: () -> Unit,
    val onClearRecentHistory: () -> Unit,
    val onClearSavedNetworkSources: () -> Unit,
    val onClearAllSettings: () -> Unit,
    val onClearAllPluginSettings: () -> Unit,
    val onResetPluginSettings: (String) -> Unit
)
